
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.5
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  file_picker: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  charset: ^0.3.0                 # 替换 gbk
  charset_converter: ^2.0.0
  charset_detector: ^1.0.0
